Vertexvis/dev-portal

docusaurus.config.js

Added an image to display when sharing the dev portal link.
Tested locally via source code
added og:image tag for preview image in sharable instances
N/A
N/A

open graph image for the site

---

docs/guides/build-your-first-app.mdx
package.json
src/pages/index.js
yarn.lock

[API-1927]: Add webhooks to homepage

---

src/pages/examples/index.js
src/pages/examples/scene-studio.js

[API-1914]: Add links for Scene Studio

---

src/pages/examples/3d-visual-analytics.js
src/pages/examples/digital-twin.js
src/pages/examples/index.js
src/pages/examples/nextjs.js
src/pages/examples/scene-studio.js
yarn.lock

[API-1914]: Lowercase

---

docs/guides/build-your-first-app.mdx
package.json
yarn.lock

[API-2013]: Update to match starter updates

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

Updating the documentation for new supported file format versions.
See documentation.
Formatting
None

[RENDER-3099] Update supported versions

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

Updating the documentation for support for Inventor 2022.
See documentation.
Formatting
None

[RENDER-3129] Support for Inventor 2022

---

docs/guides/render-your-first-scene.mdx
docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

Render your 1st scene revisions

---

LICENSE
docs/guides/build-your-first-app.mdx
docs/guides/render-your-first-scene.mdx
docusaurus.config.js
package.json
yarn.lock

[API-2206]: Update deps, company name

---

docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
static/examples/first-scene/index.html
static/examples/loading-model/index.html
yarn.lock

[API-2214]: Update default stream key

---

docs/guides/import-data.mdx

Revisions to Import data (CLI). Mostly style guide updates.

Revisions to Import data using CLI

---

docs/guides/import-data.mdx

Nested/indented notes and paragraphs under steps.

nested feedback notes and paragraphs under steps

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

Update documentation to list CreoView support.
Look at documentation.
Support for CreoView
None
None

[RENDER-3146] Creoview support

---

docusaurus.config.js
src/pages/index.js

- Update the link on the Sign Up button to go to our sign up page
- Update text and link in the CTA at the bottom of the page (to mention 100 free rendering credits)
- remove the AWS banner
Tested locally with Megan over screen share 
N/A
N/A
N/A

updates for new direct signup page

---

docs/guides/build-your-first-app.mdx
docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
docs/guides/supported-file-formats.mdx
package.json
src/pages/index.js
static/examples/first-scene/index.html
static/examples/loading-model/index.html
versioned_docs/version-beta/guides/importing-data.md
yarn.lock

[API-2257]: Update to latest NextJS code, update 'Render your first scene' with more performant deselect

---

src/components/SignUpNote.js

[API-2269]: Open in new tab

---

static/examples/hidden-parts/main.d54af17d1b2446c64afa.js

This change updates the stream key for the hidden parts demo. New stream key is good for a year. Also introduced a small improvement to the opacity level of the ghosted parts in that app.
Verify scene loads properly post deploy.
N/A
None

Updated stream key for hidden parts example

---

docusaurus.config.js
package.json
src/components/CodeExamples.js
src/components/ExamplesCta.js
src/components/Mermaid.js
src/components/SignUpNote.js
src/components/SwaggerApi.js
src/components/VertexAccordion/index.js
src/pages/api/1.0.js
src/pages/api/beta.js
src/pages/contact.js
src/pages/examples/3d-visual-analytics.js
src/pages/examples/contact.js
src/pages/examples/digital-twin.js
src/pages/examples/index.js
src/pages/examples/nextjs.js
src/pages/examples/work-instructions.js
src/pages/index.js
src/pages/support.js
yarn.lock

[PLAT-644] Update Algolia

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We need to update our supported file formats.

[PLAT-1089] Update supported file formats

---

.github/CODEOWNERS
docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
static/examples/first-scene/index.html
static/examples/loading-model/index.html

https://vertexvis.atlassian.net/browse/PLAT-1325

[PLAT-1325] Update stream keys

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We need to update our supported file formats.

[PLAT-1482] Update supported file formats

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We need to update our supported file formats.

[PLAT-1893] Update supported file formats

---

docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
static/examples/first-scene/index.html
static/examples/loading-model/index.html

Removes selection material from guides. Also updates version of Web SDK.
https://vertexvis.atlassian.net/browse/PLAT-2591

[PLAT-2591] Remove selection material APIs from guides

---

docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
static/examples/first-scene/index.html
static/examples/loading-model/index.html

[PLAT-2750] Update Stream Key

---

static/robots.txt

Added exception for Algolia crawler to fix search results.

Update robots.txt to fix search indexing

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support Creo 10 and this updates the documentation accordingly.

[PLAT-3188] Update supported file formats

---

docs/guides/authentication.mdx
docs/guides/install-sdk.mdx
docs/guides/render-static-scenes.mdx
docs/guides/render-your-first-scene.mdx
static/examples/first-scene/index.html
static/examples/loading-model/index.html

Updates the documentation to use the `vertex` urn instead of `vertexvis`

[PLAT-3139] Using new namespace for the sdk urn

---

docs/guides/render-static-scenes.mdx

Updates the link to the directions around creating a stream key.

[PLAT-3291] Update stream key link

---

docs/guides/customize-your-scene.mdx
guides.js
sidebars.js
src/components/ExampleAppNote.js
src/css/custom.css
src/pages/index.js
static/examples/change-material/index.html
static/examples/change-phantom/index.html

Adds a `Customize your scene` guide with details on the various queries and operations available through the `scene.items` method.
- Run through the guide and verify the examples work
N/A
N/A
N/A

[PLAT-3292] Add scene alteration guide

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support JT 10.9 and NX 2306 and this updates the documentation accordingly.

[PLAT-3398] Update supported file formats

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support JT 10.9, NX 2306, Parasolid 36.0, Revit 2024, and Solid Edge 2024.

[PLAT-3795] Update supported file formats

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support Solidworks 2024.

[PLAT-3956] Support for Solidworks 2024

---

docusaurus.config.js
src/pages/contact.js
src/pages/examples/contact.js
src/pages/support.js
static/specs/platform.yaml
versioned_docs/version-beta/support.md

initial vertex3d launch

---

.github/workflows/build.yml
.github/workflows/deploy.yml
docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

[PLAT-4198] Support for new file format versions

---

versioned_docs/version-beta/guides/importing-data.md

Simple update of links from help.vertexvis.com to help.vertex3d.com

updates from help.vertexvis.com to help.vertex3d.com

---

docs/guides/supported-file-formats.mdx

Creo version 11 is now supported.
Format | Updated Version
Navisworks | 2025
Creo | 11.0
https://docs.techsoft3d.com/exchange/latest/release_notes/2024.4.0.html

[PLAT-4503] Hoops update

---

docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx

Updates the viewer sdk to the latest version.

[PLAT-4505] Update viewer sdk to latest version

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support Solid Edge 2025 and Solidworks 2025.

[PLAT-5600] Support for Solid Edge 2025 and Solidworks 2025

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

[PLAT-5870] Support for NX 2412

---

docs/guides/supported-file-formats.mdx
versioned_docs/version-beta/guides/importing-data.md

We now support Parasolid 37.1.

[PLAT-6179] Support for Parasolid 37.1

---

docs/guides/customize-your-scene.mdx
docs/guides/import-data-with-api.mdx
docs/guides/import-data.mdx
docs/guides/install-sdk.mdx
docs/guides/render-your-first-scene.mdx
docs/guides/webhooks.mdx
docusaurus.config.js
static/examples/change-material/index.html
static/examples/change-phantom/index.html
static/examples/first-scene/index.html
static/examples/load-model/configure-scene.html
static/examples/load-model/create-scene.html
static/examples/loading-model/index.html
static/examples/scene-operations/overview.html
versioned_docs/version-beta/guides/importing-data.md
versioned_docs/version-beta/sdk/sdk-web-getting-started.md

This PR updates the stream keys and sdk version used in our examples.

[PLAT-6352] Update sdk version and stream keys

---

docs/guides/webhooks.mdx

Adding documentation for the new file jobs webhook

PLAT-6447: adding documentation for file jobs webhook

---

docs/guides/authentication.mdx
docs/guides/collaboration-apis.mdx
docs/guides/user-management.mdx
sidebars.js

Adds documentation for our Collaboration APIs, Token Exchanges and User Management APIs.
https://vertexvis.atlassian.net/browse/PLAT-6882
https://vertexvis.atlassian.net/browse/PLAT-6881
https://vertexvis.atlassian.net/browse/PLAT-6880

[PLAT-6882][PLAT-6881][PLAT-6880] Documentation for Collaboration APIs
